swipe:
  4:
    left:
      command: 'xdotool key ctrl+shift+Tab'
    right:
      command: 'xdotool key ctrl+Tab'
  3:
    left:
      command: 'i3-msg workspace prev'
    right:
      command: 'i3-msg workspace next'
pinch:
  in:
    command: 'xdotool key ctrl+shift+plus'
  out:
    command: 'xdotool key ctrl+shift+minus'
